"""add order fields and installation access_token

Revision ID: 877df32a3031
Revises: f94cc6d49fa4
Create Date: 2026-03-21 17:41:06.857045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877df32a3031'
down_revision: Union[str, Sequence[str], None] = 'f94cc6d49fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(length=200), nullable=True))
    op.add_column('orders', sa.Column('raw_phone', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('tracking_url', sa.String(length=500), nullable=True))
    op.add_column('store_installations', sa.Column('access_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_installations', 'access_token')
    op.drop_column('orders', 'tracking_url')
    op.drop_column('orders', 'raw_phone')
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###
