"""initial schema: stores, users, orders, notifications

Revision ID: f94cc6d49fa4
Revises: 
Create Date: 2026-03-21 17:34:13.233785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94cc6d49fa4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_store_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_store_id')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('normalized_phone', sa.String(length=20), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('notified_in_transit', sa.Boolean(), nullable=True),
    sa.Column('notified_delivered', sa.Boolean(), nullable=True),
    sa.Column('notification_status', sa.String(length=50), nullable=True),
    sa.Column('notification_error', sa.Text(), nullable=True),
    sa.Column('last_message_type', sa.String(length=50), nullable=True),
    sa.Column('last_template_name', sa.String(length=100), nullable=True),
    sa.Column('last_message_preview', sa.Text(), nullable=True),
    sa.Column('first_notification_at', sa.DateTime(), nullable=True),
    sa.Column('last_notification_at', sa.DateTime(), nullable=True),
    sa.Column('invalid_phone', sa.Boolean(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_status_change_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_current_status', 'orders', ['current_status'], unique=False)
    op.create_index('idx_orders_store_id', 'orders', ['store_id'], unique=False)
    op.create_index('idx_orders_store_status', 'orders', ['store_id', 'current_status'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('store_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('order_source_type', sa.String(length=50), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_installations_id'), 'store_installations', ['id'], unique=False)
    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('weraha_enabled', sa.Boolean(), nullable=True),
    sa.Column('weraha_account_reference', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_phone_number_id', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_business_account_id', sa.String(length=100), nullable=True),
    sa.Column('template_in_transit', sa.String(length=100), nullable=True),
    sa.Column('template_delivered', sa.String(length=100), nullable=True),
    sa.Column('onboarding_status', sa.String(length=50), nullable=True),
    sa.Column('test_message_status', sa.String(length=50), nullable=True),
    sa.Column('last_onboarding_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_index(op.f('ix_store_settings_id'), 'store_settings', ['id'], unique=False)
    op.create_table('store_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_store_users_id'), 'store_users', ['id'], unique=False)
    op.create_table('notification_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider_message_id', sa.String(length=150), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_notification_attempts_order', 'notification_attempts', ['order_id'], unique=False)
    op.create_index('idx_notification_attempts_store', 'notification_attempts', ['store_id'], unique=False)
    op.create_index(op.f('ix_notification_attempts_id'), 'notification_attempts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_attempts_id'), table_name='notification_attempts')
    op.drop_index('idx_notification_attempts_store', table_name='notification_attempts')
    op.drop_index('idx_notification_attempts_order', table_name='notification_attempts')
    op.drop_table('notification_attempts')
    op.drop_index(op.f('ix_store_users_id'), table_name='store_users')
    op.drop_table('store_users')
    op.drop_index(op.f('ix_store_settings_id'), table_name='store_settings')
    op.drop_table('store_settings')
    op.drop_index(op.f('ix_store_installations_id'), table_name='store_installations')
    op.drop_table('store_installations')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index('idx_orders_store_status', table_name='orders')
    op.drop_index('idx_orders_store_id', table_name='orders')
    op.drop_index('idx_orders_current_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
